title: Nikolay Marinov
email: nikolay.marinov@gu.se
description: "Political Scientist | Democracy, Elections, Foreign Interventions"
baseurl: "" # leave blank for GitHub Pages
url: "https://nikolayvmarinov.github.io"

remote_theme: pkumar/academicpages

# Google Scholar, social links
author:
  name: "Nikolay Marinov"
  image: "assets/images/NicholasMarinov.jpg"
  bio: "I am a political scientist studying how international and domestic forces shape democracy..."
  links:
    - name: "Google Scholar"
      url: "https://scholar.google.com/citations?user=nYFJRskAAAAJ&hl=en"
    - name: "Facebook"
      url: "https://www.facebook.com/nikolay.marinov.5/"
    - name: "Bluesky"
      url: "https://bsky.app/profile/professorniki.bsky.social"
    - name: "YouTube"
      url: "https://www.youtube.com/channel/UCr7Z7R7fGxRBWRDThcY1KQA"


plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji